export const environment = {
  production: false,
  useMock: false,
  apiUrl: '',
  mockUrl: {
    login: 'assets/mocks/login-mock.json',
    vacation: 'assets/mocks/vacation-mock.json',
    birthday: 'assets/mocks/birthday-mock.json',
    disabilities: 'assets/mocks/disabilities-mock.json',
    calamity: 'assets/mocks/calamity-mock.json',
    birthdayLeader: 'assets/mocks/birthday-leader-mock.json',
    calamityLeader: 'assets/mocks/calamity-leader-mock.json',
    vacationLeader: 'assets/mocks/vacation-leader-mock.json',
    disabilitiesLeader: 'assets/mocks/disabilities-leader-mock.json'
  },
  endpoint: {
    login: '/talento/login',
    vacation: '/talento/listarVacaciones',
    createVacation: '/talento/crearVacaciones',
    birthday: '/talento/listarDiasCumpleanios',
    createBirthday: '/talento/crearDiaCumpleanio',
    disabilities: '/talento/listarIncapacidades',
    createDisability: '/talento/crearIncapacidad',
    calamity: '/talento/listarCalamidades',
    createCalamity: '/talento/crearCalamidad',
    vacationLeader: '/talento/listarVacacionesPendientes',
    approveVacation: '/talento/aprobarVacaciones',
    rejectVacation: '/talento/rechazarVacaciones',
    birthdayLeader: '/talento/listarDiasCumpleaniosPendientes',
    approveBirthday: '/talento/aprobarDiaCumpleanio',
    rejectBirthday: '/talento/rechazarDiaCumpleanio',
    disabilitiesLeader: '/talento/listarIncapacidadesPendientes',
    approveDisability: '/talento/aprobarIncapacidad',
    rejectDisability: '/talento/rechazarIncapacidad',
    calamityLeader: '/talento/listarCalamidadesPendientes',
    approveCalamity: '/talento/aprobarCalamidad',
    rejectCalamity: '/talento/rechazarCalamidad',
    closeMonth: '/talento/cierreMesSolicitudes',
    monthClosureStatus: '/talento/cierreMes',
    peopleReport: '/talento/consolidadoSolicitudes'
  }
};
